config/routes.rb
Rails.application.routes.draw do


  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'usuarios/new'

  resources :filmes

  root :to => "filmes#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/filme.rb
class Filme < ApplicationRecord

  has_attached_file :imagem, styles: { medium: "6000x400", thumb: "200x200" }
  validates_attachment_content_type :imagem, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/filmes_controller.rb
class FilmesController < ApplicationController

  before_action :authenticate_user!, :except=>[:show, :index]

  def index
    @filmes = Filme.all
  end

  def show

    @filme = Filme.find(params[:id])

  end


 def create

      @filme = Filme.new(filmes_params)

   if @filme.save
     redirect_to @filme
   else
     render 'new'
   end
 end


 private
   def filmes_params
     params.require(:filmes).permit(:title, :originalTitle, :slug, :sinopse, :duration, :likes, :isPublished, :imagem, :listaAtores)
   end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/filmes/index.html.erb
<h1>óia n é que foi. :D</h1>

<% if user_signed_in? %>
  <h2><%= link_to 'Add Filme', new_filme_path %></h2>
<% end %>

<% @filmes.each do |filme| %>

     <h2><%= filme.id %></h2>
     <h3><%= filme.title %></h3>
     <h3><%= filme.originalTitle %></h3>
     <h3><%= filme.slug %></h3>
     <h3><%= filme.sinopse %></h3>
     <h3><%= filme.duration %></h3>
     <h3><%= filme.likes %></h3>
     <h3><%= filme.isPublished %></h3>
     <h3>  <%= image_tag filme.imagem.url(:thumb) %>
</h3>



  <% end %>

</table>

app/views/filmes/new.html.erb
<h1>NEW</h1>

<p id="notice"><%= notice %></p>



<%= form_with scope: :filmes, html: { multipart: true }, url: filmes_path, local: true do |form| %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :originalTitle %><br>
    <%= form.text_field :originalTitle %>
  </p>

  <p>
    <%= form.label :sinopse %><br>
    <%= form.text_field :sinopse %>
  </p>

  <p>
    <%= form.label :duration %><br>
    <%= form.text_field :duration %>
  </p>

  <p>
    <%= form.label :likes %><br>
    <%= form.text_field :likes %>
  </p>

  <p>
    <%= form.label :isPublished %><br>
    <%= form.text_field :isPublished %>
  </p>
  <p>
    <%= form.file_field :imagem %>
  </p>

  <p>
    Lista de Atores<br>
    <%= form.text_field :listaAtores %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', filmes_path %>

app/views/filmes/show.html.erb
<h1>SHOW</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>id:</strong>
  <%= @filme.id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @filme.title %>
</p>

<p>
  <strong>Original Title:</strong>
  <%= @filme.originalTitle %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @filme.slug %>
</p>

<p>
  <strong>Sinopse:</strong>
  <%= @filme.sinopse %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @filme.duration %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @filme.likes %>
</p>

<p>
  <strong>isPublished:</strong>
  <%= @filme.duration %>
</p>

<p>
  <%= image_tag @filme.imagem.url(:thumb) %>
</p>

<%= link_to 'Edit', edit_filme_path(@filme) %> |
<%= link_to 'Back', filmes_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<% @filmes.each do |filme| %>

     <h2><%= filme.id %></h2>
     <h3><%= filme.title %></h3>
     <h3><%= filme.originalTitle %></h3>
     <h3><%= filme.slug %></h3>
     <h3><%= filme.sinopse %></h3>
     <h3><%= filme.duration %></h3>
     <h3><%= filme.likes %></h3>
     <h3><%= filme.isPublished %></h3>
     <h3>  <%= image_tag filme.imagem.url(:thumb) %>
</h3>



  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moviecine</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logado como: <strong><%= current_user.email %></strong>.
  <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
    <%= yield %>
  </body>
</html>